// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function ConnectIBKR():Promise<domain.AppState>;

export function DisconnectIBKR():Promise<domain.AppState>;

export function GetState():Promise<domain.AppState>;

export function RunAnalysisNow():Promise<domain.AppState>;

export function SaveSettings(arg1:domain.Settings):Promise<domain.AppState>;
