// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectIBKR() {
  return window['go']['main']['App']['ConnectIBKR']();
}

export function DisconnectIBKR() {
  return window['go']['main']['App']['DisconnectIBKR']();
}

export function GetState() {
  return window['go']['main']['App']['GetState']();
}

export function RunAnalysisNow() {
  return window['go']['main']['App']['RunAnalysisNow']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}
